/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import modelo.LoginDAO;
import modelo.login;

/**
 *
 * @author EDER
 */
public class Login extends javax.swing.JFrame {

    login lg = new login();
    LoginDAO login = new LoginDAO();
    
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
    }
    
    public void validar() {
        
        String correo = jTextFieldTxtCorreo.getText();
        String pass = String.valueOf(jPasswordFieldTxtPass.getPassword());
        
        if (!"".equals(correo) || !"".equals(pass)) {
            
            
            lg = login.log(correo, pass);
            
            if (lg.getCorreo() != null && lg.getPass() != null) {
                
                SistemaMEC sis = new SistemaMEC();
                sis.setVisible(true);
                dispose();
                
                
            } else {
                
                JOptionPane.showMessageDialog(null, "CORREO o CONTRASEÑA incorrecta");
                
            } 
            
            
        }
        
    }
    
    //Icono del JFrame 
    
    @Override
    public Image getIconImage () {
        
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/logo.png"));
        
        return retValue;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCONTENEDOR = new javax.swing.JPanel();
        jLabelAVATAR = new javax.swing.JLabel();
        jLabelHEADER = new javax.swing.JLabel();
        jLabelTxtCorreo = new javax.swing.JLabel();
        jTextFieldTxtCorreo = new javax.swing.JTextField();
        jLabelTXTCONTRASEÑA = new javax.swing.JLabel();
        jPasswordFieldTxtPass = new javax.swing.JPasswordField();
        jCheckBoxGUARDARCONTRA = new javax.swing.JCheckBox();
        jButtonINGRESAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonOLVIDARCONTRA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelCONT = new javax.swing.JLabel();
        jButtonSALIR = new javax.swing.JButton();
        jLabelBGLOGIN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelCONTENEDOR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAVATAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Avatar_Container (1).png"))); // NOI18N
        jPanelCONTENEDOR.add(jLabelAVATAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, -1));

        jLabelHEADER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Header (1).jpg"))); // NOI18N
        jPanelCONTENEDOR.add(jLabelHEADER, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, -6, 450, 120));

        jLabelTxtCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTxtCorreo.setForeground(new java.awt.Color(227, 6, 20));
        jLabelTxtCorreo.setText("Usuario");
        jPanelCONTENEDOR.add(jLabelTxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanelCONTENEDOR.add(jTextFieldTxtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 370, 40));

        jLabelTXTCONTRASEÑA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTXTCONTRASEÑA.setForeground(new java.awt.Color(227, 6, 20));
        jLabelTXTCONTRASEÑA.setText("Contraseña");
        jPanelCONTENEDOR.add(jLabelTXTCONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        jPanelCONTENEDOR.add(jPasswordFieldTxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 370, 40));

        jCheckBoxGUARDARCONTRA.setForeground(new java.awt.Color(227, 6, 20));
        jCheckBoxGUARDARCONTRA.setText("Guardar contraseña");
        jCheckBoxGUARDARCONTRA.setBorder(null);
        jCheckBoxGUARDARCONTRA.setContentAreaFilled(false);
        jPanelCONTENEDOR.add(jCheckBoxGUARDARCONTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, -1, -1));

        jButtonINGRESAR.setBackground(new java.awt.Color(227, 6, 20));
        jButtonINGRESAR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonINGRESAR.setForeground(new java.awt.Color(255, 255, 255));
        jButtonINGRESAR.setText("Ingresar");
        jButtonINGRESAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonINGRESARMouseClicked(evt);
            }
        });
        jButtonINGRESAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonINGRESARActionPerformed(evt);
            }
        });
        jPanelCONTENEDOR.add(jButtonINGRESAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 410, 370, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Lock.png"))); // NOI18N
        jPanelCONTENEDOR.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

        jButtonOLVIDARCONTRA.setForeground(new java.awt.Color(153, 153, 153));
        jButtonOLVIDARCONTRA.setText("¿Olvidaste tu contraseña?");
        jButtonOLVIDARCONTRA.setBorderPainted(false);
        jButtonOLVIDARCONTRA.setContentAreaFilled(false);
        jPanelCONTENEDOR.add(jButtonOLVIDARCONTRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/By NETCODEX TECH.png"))); // NOI18N
        jPanelCONTENEDOR.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        jLabelCONT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Card_Content.jpg"))); // NOI18N
        jLabelCONT.setText("jLabel1");
        jPanelCONTENEDOR.add(jLabelCONT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 450, 380));

        getContentPane().add(jPanelCONTENEDOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 450, 490));

        jButtonSALIR.setBackground(new java.awt.Color(19, 70, 147));
        jButtonSALIR.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonSALIR.setForeground(new java.awt.Color(227, 6, 20));
        jButtonSALIR.setText("SALIR");
        jButtonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, -1, -1));

        jLabelBGLOGIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LoginBg Comfenalco.png"))); // NOI18N
        getContentPane().add(jLabelBGLOGIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSALIRActionPerformed

    private void jButtonINGRESARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonINGRESARMouseClicked
        
    }//GEN-LAST:event_jButtonINGRESARMouseClicked

    private void jButtonINGRESARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonINGRESARActionPerformed
        validar();
    }//GEN-LAST:event_jButtonINGRESARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonINGRESAR;
    private javax.swing.JButton jButtonOLVIDARCONTRA;
    private javax.swing.JButton jButtonSALIR;
    private javax.swing.JCheckBox jCheckBoxGUARDARCONTRA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAVATAR;
    private javax.swing.JLabel jLabelBGLOGIN;
    private javax.swing.JLabel jLabelCONT;
    private javax.swing.JLabel jLabelHEADER;
    private javax.swing.JLabel jLabelTXTCONTRASEÑA;
    private javax.swing.JLabel jLabelTxtCorreo;
    private javax.swing.JPanel jPanelCONTENEDOR;
    private javax.swing.JPasswordField jPasswordFieldTxtPass;
    private javax.swing.JTextField jTextFieldTxtCorreo;
    // End of variables declaration//GEN-END:variables
}
