/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cliente;
import modelo.ClienteDao;
import java.util.List;
import modelo.Empleados;
import modelo.EmpleadosDao;
import modelo.Mantenimiento;
import modelo.MantenimientoDao;

//Filtro de busqueda//
/**
 *
 * @author EDER
 */
public class SistemaMEC extends javax.swing.JFrame {

    Cliente cl = new Cliente();
    ClienteDao client = new ClienteDao();
    Empleados em = new Empleados();
    EmpleadosDao EmDao = new EmpleadosDao();
    Mantenimiento man = new Mantenimiento();
    MantenimientoDao ManDao = new MantenimientoDao();
    DefaultTableModel modelo = new DefaultTableModel();

    public SistemaMEC() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(getIconImage());
        IdCliente.setVisible(false);
        IdEmpleados.setVisible(false);
        IdMantenimiento.setVisible(false);
    }

    public void ListarCliente() {

        List<Cliente> ListarCl = client.ListarCliente();
        modelo = (DefaultTableModel) jTableCliente.getModel();
        Object[] ob = new Object[7];

        for (int i = 0; i < ListarCl.size(); i++) {

            ob[0] = ListarCl.get(i).getId();
            ob[1] = ListarCl.get(i).getDocumento();
            ob[2] = ListarCl.get(i).getNombre();
            ob[3] = ListarCl.get(i).getApellidos();
            ob[4] = ListarCl.get(i).getCorreo();
            ob[5] = ListarCl.get(i).getTelefono();
            ob[6] = ListarCl.get(i).getEmpresa();
            modelo.addRow(ob);
        }

        jTableCliente.setModel(modelo);
    }

    public void ListarEmpleados() {

        List<Empleados> ListarEm = EmDao.ListarEmpleados();
        modelo = (DefaultTableModel) jTableEmpleados2.getModel();
        Object[] ob = new Object[7];

        for (int i = 0; i < ListarEm.size(); i++) {

            ob[0] = ListarEm.get(i).getId();
            ob[1] = ListarEm.get(i).getDocumento();
            ob[2] = ListarEm.get(i).getNombre();
            ob[3] = ListarEm.get(i).getApellidos();
            ob[4] = ListarEm.get(i).getCorreo();
            ob[5] = ListarEm.get(i).getTelefono();
            ob[6] = ListarEm.get(i).getCargo();
            modelo.addRow(ob);
        }

        jTableEmpleados2.setModel(modelo);
    }

    public void ListarMantenimiento() {

        List<Mantenimiento> ListarMan = ManDao.ListarMantenimiento();
        modelo = (DefaultTableModel) jTableMantenimiento.getModel();
        Object[] ob = new Object[10];

        for (int i = 0; i < ListarMan.size(); i++) {

            ob[0] = ListarMan.get(i).getId();
            ob[1] = ListarMan.get(i).getNinventario();
            ob[2] = ListarMan.get(i).getIdcliente();
            ob[3] = ListarMan.get(i).getMantenimiento();
            ob[4] = ListarMan.get(i).getDescripcion();
            ob[5] = ListarMan.get(i).getMarca();
            ob[6] = ListarMan.get(i).getModelo();
            ob[7] = ListarMan.get(i).getSerial();
            ob[8] = ListarMan.get(i).getFechaentrada();
            ob[9] = ListarMan.get(i).getFechasalida();
            modelo.addRow(ob);
        }

        jTableMantenimiento.setModel(modelo);
    }

    public void LimpiarTable() {

        for (int i = 0; i < modelo.getRowCount(); i++) {

            modelo.removeRow(i);
            i = i - 1;

        }

    }

    public void BuscarCliente(String buscar) {

        ClienteDao CDAO = new ClienteDao();
        DefaultTableModel modelo = CDAO.BuscarCliente(buscar);

        jTableCliente.setModel(modelo);

    }

    public void BuscarEmpleados(String buscar) {

        EmpleadosDao EDAO = new EmpleadosDao();
        DefaultTableModel modelo = EDAO.BuscarEmpleados(buscar);

        jTableEmpleados2.setModel(modelo);

    }

    public void BuscarMantenimiento(String buscar) {

        MantenimientoDao MDAO = new MantenimientoDao();
        DefaultTableModel modelo = MDAO.BuscarMantenimiento(buscar);

        jTableMantenimiento.setModel(modelo);

    }

    //Icono del JFrame
    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/logo.png"));

        return retValue;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonSALIR = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelBANNERSIS = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldDocumentoCliente = new javax.swing.JTextField();
        jTextFieldNombreCliente = new javax.swing.JTextField();
        jTextFieldApellidosCilente = new javax.swing.JTextField();
        jTextFieldCorreoCliente = new javax.swing.JTextField();
        jTextFieldTelefonoCliente = new javax.swing.JTextField();
        jTextFieldEmpresaCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jButtonCrearCliente = new javax.swing.JButton();
        jButtonActualizarCliente = new javax.swing.JButton();
        jButtonEliminarCliente = new javax.swing.JButton();
        IdCliente = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldB_cliente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldNinventarioMan = new javax.swing.JTextField();
        jTextFieldIdclienteMan = new javax.swing.JTextField();
        jTextFieldDescripcionMan = new javax.swing.JTextField();
        jTextFieldMarcaMan = new javax.swing.JTextField();
        IdMantenimiento = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableMantenimiento = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldModeloMan = new javax.swing.JTextField();
        jTextFieldSerialMan = new javax.swing.JTextField();
        jTextFieldFeMan = new javax.swing.JTextField();
        jTextFieldFsMan = new javax.swing.JTextField();
        jButtonCrearMan = new javax.swing.JButton();
        jButtonActualizarMan = new javax.swing.JButton();
        jButtonEliminarMan = new javax.swing.JButton();
        jTextFieldMantenimientoMan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldB_Mantenimiento = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldDocumentoEmpleados = new javax.swing.JTextField();
        jTextFieldNombreEmpleados = new javax.swing.JTextField();
        jTextFieldApellidosEmpleados = new javax.swing.JTextField();
        jTextFieldCorreoEmpleados = new javax.swing.JTextField();
        jTextFieldTelefonoEmpleados = new javax.swing.JTextField();
        jTextFieldCargoEmpleados = new javax.swing.JTextField();
        IdEmpleados = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEmpleados2 = new javax.swing.JTable();
        jButtonCrearEmpleados = new javax.swing.JButton();
        jButtonActualizarEmpleados = new javax.swing.JButton();
        jButtonEliminarEmpleados = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldB_Empleados = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setBackground(new java.awt.Color(227, 5, 19));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Usuario.png"))); // NOI18N
        jButton5.setText("Clientes");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(227, 5, 19));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mantenimiento.png"))); // NOI18N
        jButton7.setText("Mantenimiento");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(227, 5, 19));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Trabajador.png"))); // NOI18N
        jButton6.setText("Empleados");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/L Comfenalco PNG.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/By NETCODEX TECH.png"))); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(60, 60, 60)
                .addComponent(jButton7)
                .addGap(60, 60, 60)
                .addComponent(jButton6)
                .addGap(172, 172, 172)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 720));

        jButtonSALIR.setBackground(new java.awt.Color(19, 70, 147));
        jButtonSALIR.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButtonSALIR.setForeground(new java.awt.Color(227, 6, 20));
        jButtonSALIR.setText("SALIR");
        jButtonSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(19, 70, 147));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(227, 6, 20));
        jButton1.setText("CERRAR SESIÓN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 40, -1, -1));

        jLabelBANNERSIS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Header SCMEC.png"))); // NOI18N
        getContentPane().add(jLabelBANNERSIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 1110, 170));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Documento:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Apellidos:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Teléfono:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Empresa:");

        jTextFieldCorreoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCorreoClienteActionPerformed(evt);
            }
        });

        jTextFieldTelefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoClienteActionPerformed(evt);
            }
        });

        jTextFieldEmpresaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmpresaClienteActionPerformed(evt);
            }
        });

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DOCUMENTO", "NOMBRE", "APELLIDOS", "CORREO", "TELÉFONO", "EMPRESA"
            }
        ));
        jTableCliente.setSelectionBackground(new java.awt.Color(16, 68, 146));
        jTableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCliente);
        if (jTableCliente.getColumnModel().getColumnCount() > 0) {
            jTableCliente.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableCliente.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTableCliente.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableCliente.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableCliente.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableCliente.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTableCliente.getColumnModel().getColumn(6).setPreferredWidth(55);
        }

        jButtonCrearCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Crear - +.png"))); // NOI18N
        jButtonCrearCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrearCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearClienteActionPerformed(evt);
            }
        });

        jButtonActualizarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actualizar -.png"))); // NOI18N
        jButtonActualizarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonActualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarClienteActionPerformed(evt);
            }
        });

        jButtonEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar - X.png"))); // NOI18N
        jButtonEliminarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarClienteActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Buscar:");

        jTextFieldB_cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldB_clienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7)
                    .addComponent(jButtonCrearCliente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonActualizarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEliminarCliente))
                    .addComponent(jTextFieldEmpresaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldApellidosCilente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldB_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldDocumentoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldApellidosCilente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldCorreoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldTelefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldEmpresaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCrearCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonActualizarCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEliminarCliente))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldB_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Clientes", jPanel2);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("N° de invetario:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("ID-Cliente:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Mantenimiento:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Descripción:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Marca:");

        jTableMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "N°INVENTARIO", "ID-CLIENTE", "MANTENIMIENTO", "DESCRIPCIÓN", "MARCA", "MODELO", "SERIAL", "FECHA-ENTRADA", "FECHA-SALIDA"
            }
        ));
        jTableMantenimiento.setSelectionBackground(new java.awt.Color(16, 68, 146));
        jTableMantenimiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMantenimientoMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTableMantenimiento);
        if (jTableMantenimiento.getColumnModel().getColumnCount() > 0) {
            jTableMantenimiento.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableMantenimiento.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTableMantenimiento.getColumnModel().getColumn(2).setPreferredWidth(80);
            jTableMantenimiento.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableMantenimiento.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableMantenimiento.getColumnModel().getColumn(5).setPreferredWidth(50);
            jTableMantenimiento.getColumnModel().getColumn(6).setPreferredWidth(55);
            jTableMantenimiento.getColumnModel().getColumn(7).setPreferredWidth(50);
            jTableMantenimiento.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTableMantenimiento.getColumnModel().getColumn(9).setPreferredWidth(100);
        }

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel22.setText("Modelo:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setText("N° Serial:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel24.setText("Fecha de entrada:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel25.setText("Fecha de salida:");

        jButtonCrearMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Crear - +.png"))); // NOI18N
        jButtonCrearMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearManActionPerformed(evt);
            }
        });

        jButtonActualizarMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actualizar -.png"))); // NOI18N
        jButtonActualizarMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarManActionPerformed(evt);
            }
        });

        jButtonEliminarMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar - X.png"))); // NOI18N
        jButtonEliminarMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarManActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setText("Buscar:");

        jTextFieldB_Mantenimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldB_MantenimientoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(IdMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap(93, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jButtonCrearMan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNinventarioMan)
                    .addComponent(jTextFieldIdclienteMan)
                    .addComponent(jTextFieldMarcaMan)
                    .addComponent(jTextFieldModeloMan)
                    .addComponent(jTextFieldSerialMan)
                    .addComponent(jTextFieldFeMan)
                    .addComponent(jTextFieldFsMan)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButtonActualizarMan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEliminarMan))
                    .addComponent(jTextFieldMantenimientoMan)
                    .addComponent(jTextFieldDescripcionMan))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldB_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IdMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldNinventarioMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldIdclienteMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextFieldMantenimientoMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jTextFieldDescripcionMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTextFieldMarcaMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jTextFieldModeloMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextFieldSerialMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jTextFieldFeMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25)
                            .addComponent(jTextFieldFsMan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCrearMan)
                            .addComponent(jButtonEliminarMan)
                            .addComponent(jButtonActualizarMan))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldB_Mantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mantenimiento", jPanel3);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Doucmento:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Apellidos:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Correo:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Teléfono:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Cargo:");

        jTableEmpleados2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DOCUMENTO", "NOMBRE", "APELLIDOS", "CORREO", "TELÉFONO", "CARGO"
            }
        ));
        jTableEmpleados2.setSelectionBackground(new java.awt.Color(16, 68, 146));
        jTableEmpleados2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpleados2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableEmpleados2);
        if (jTableEmpleados2.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados2.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableEmpleados2.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTableEmpleados2.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTableEmpleados2.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableEmpleados2.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableEmpleados2.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTableEmpleados2.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        jButtonCrearEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Crear - +.png"))); // NOI18N
        jButtonCrearEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearEmpleadosActionPerformed(evt);
            }
        });

        jButtonActualizarEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actualizar -.png"))); // NOI18N
        jButtonActualizarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarEmpleadosActionPerformed(evt);
            }
        });

        jButtonEliminarEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar - X.png"))); // NOI18N
        jButtonEliminarEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarEmpleadosActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Buscar:");

        jTextFieldB_Empleados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldB_EmpleadosKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(IdEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jButtonCrearEmpleados))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonActualizarEmpleados)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEliminarEmpleados))
                            .addComponent(jTextFieldDocumentoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNombreEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldApellidosEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCorreoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTelefonoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCargoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldB_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(IdEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldDocumentoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldNombreEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldApellidosEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldCorreoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextFieldTelefonoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldCargoEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCrearEmpleados, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonActualizarEmpleados, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonEliminarEmpleados)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldB_Empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empleados", jPanel4);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 1110, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        LimpiarTable();
        ListarCliente();
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        LimpiarTable();
        ListarMantenimiento();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        LimpiarTable();
        ListarEmpleados();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButtonEliminarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarEmpleadosActionPerformed
        // TODO add your handling code here:
        if (!"".equals(IdEmpleados.getText())) {

            int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar?");
            if (pregunta == 0) {

                int id = Integer.parseInt(IdEmpleados.getText());
                EmDao.EliminarEmpleados(id);
                LimpiarTable();
                ListarEmpleados();

            }

        } else {

            JOptionPane.showMessageDialog(null, "Seleccione una fila");

        }
    }//GEN-LAST:event_jButtonEliminarEmpleadosActionPerformed

    private void jButtonActualizarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarEmpleadosActionPerformed
        // TODO add your handling code here:
        if ("".equals(IdEmpleados.getText())) {

            JOptionPane.showMessageDialog(null, "Seleccione una fila");

        } else {

            if (!"".equals(jTextFieldDocumentoEmpleados.getText()) && !"".equals(jTextFieldNombreEmpleados.getText()) && !"".equals(jTextFieldApellidosEmpleados.getText()) && !"".equals(jTextFieldCorreoEmpleados.getText()) && !"".equals(jTextFieldTelefonoEmpleados.getText()) && !"".equals(jTextFieldCargoEmpleados.getText())) {

                em.setDocumento(Integer.parseInt(jTextFieldDocumentoEmpleados.getText()));
                em.setNombre(jTextFieldNombreEmpleados.getText());
                em.setApellidos(jTextFieldApellidosEmpleados.getText());
                em.setCorreo(jTextFieldCorreoEmpleados.getText());
                em.setTelefono(Integer.parseInt(jTextFieldTelefonoEmpleados.getText()));
                em.setCargo(jTextFieldCargoEmpleados.getText());
                em.setId(Integer.parseInt(IdEmpleados.getText()));

                EmDao.ModificarEmpleados(em);
                LimpiarTable();
                ListarEmpleados();

            } else {

                JOptionPane.showMessageDialog(null, "Los campos están vacios");

            }
        }
    }//GEN-LAST:event_jButtonActualizarEmpleadosActionPerformed

    private void jButtonCrearEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearEmpleadosActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTextFieldDocumentoEmpleados.getText()) && !"".equals(jTextFieldNombreEmpleados.getText()) && !"".equals(jTextFieldApellidosEmpleados.getText()) && !"".equals(jTextFieldCorreoEmpleados.getText()) && !"".equals(jTextFieldTelefonoEmpleados.getText()) && !"".equals(jTextFieldCargoEmpleados.getText())) {

            em.setDocumento(Integer.parseInt(jTextFieldDocumentoEmpleados.getText()));
            em.setNombre(jTextFieldNombreEmpleados.getText());
            em.setApellidos(jTextFieldApellidosEmpleados.getText());
            em.setCorreo(jTextFieldCorreoEmpleados.getText());
            em.setTelefono(Integer.parseInt(jTextFieldTelefonoEmpleados.getText()));
            em.setCargo(jTextFieldCargoEmpleados.getText());
            EmDao.RegistrarEmpleados(em);
            LimpiarTable();
            ListarEmpleados();
            JOptionPane.showMessageDialog(null, "Empleado REGISTRADO");

        } else {

            JOptionPane.showMessageDialog(null, "Los campos están vacios");

        }
    }//GEN-LAST:event_jButtonCrearEmpleadosActionPerformed

    private void jTableEmpleados2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpleados2MouseClicked
        // TODO add your handling code here:
        int fila = jTableEmpleados2.rowAtPoint(evt.getPoint());
        IdEmpleados.setText(jTableEmpleados2.getValueAt(fila, 0).toString());
        jTextFieldDocumentoEmpleados.setText(jTableEmpleados2.getValueAt(fila, 1).toString());
        jTextFieldNombreEmpleados.setText(jTableEmpleados2.getValueAt(fila, 2).toString());
        jTextFieldApellidosEmpleados.setText(jTableEmpleados2.getValueAt(fila, 3).toString());
        jTextFieldCorreoEmpleados.setText(jTableEmpleados2.getValueAt(fila, 4).toString());
        jTextFieldTelefonoEmpleados.setText(jTableEmpleados2.getValueAt(fila, 5).toString());
        jTextFieldCargoEmpleados.setText(jTableEmpleados2.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_jTableEmpleados2MouseClicked

    private void jTableMantenimientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMantenimientoMouseClicked
        // TODO add your handling code here:
        int fila = jTableMantenimiento.rowAtPoint(evt.getPoint());
        IdMantenimiento.setText(jTableMantenimiento.getValueAt(fila, 0).toString());
        jTextFieldNinventarioMan.setText(jTableMantenimiento.getValueAt(fila, 1).toString());
        jTextFieldIdclienteMan.setText(jTableMantenimiento.getValueAt(fila, 2).toString());
        jTextFieldMantenimientoMan.setText(jTableMantenimiento.getValueAt(fila, 3).toString());
        jTextFieldDescripcionMan.setText(jTableMantenimiento.getValueAt(fila, 4).toString());
        jTextFieldMarcaMan.setText(jTableMantenimiento.getValueAt(fila, 5).toString());
        jTextFieldModeloMan.setText(jTableMantenimiento.getValueAt(fila, 6).toString());
        jTextFieldSerialMan.setText(jTableMantenimiento.getValueAt(fila, 7).toString());
        jTextFieldFeMan.setText(jTableMantenimiento.getValueAt(fila, 8).toString());
        jTextFieldFsMan.setText(jTableMantenimiento.getValueAt(fila, 9).toString());
    }//GEN-LAST:event_jTableMantenimientoMouseClicked

    private void jButtonEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarClienteActionPerformed
        // TODO add your handling code here:
        if (!"".equals(IdCliente.getText())) {

            int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar?");
            if (pregunta == 0) {

                int id = Integer.parseInt(IdCliente.getText());
                client.EliminarCliente(id);
                LimpiarTable();
                ListarCliente();

            }

        } else {

            JOptionPane.showMessageDialog(null, "Seleccione una fila");

        }
    }//GEN-LAST:event_jButtonEliminarClienteActionPerformed

    private void jButtonActualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarClienteActionPerformed
        // TODO add your handling code here:
        if ("".equals(IdCliente.getText())) {

            JOptionPane.showMessageDialog(null, "Seleccione una fila");

        } else {

            if (!"".equals(jTextFieldDocumentoCliente.getText()) && !"".equals(jTextFieldNombreCliente.getText()) && !"".equals(jTextFieldApellidosCilente.getText()) && !"".equals(jTextFieldCorreoCliente.getText()) && !"".equals(jTextFieldTelefonoCliente.getText()) && !"".equals(jTextFieldEmpresaCliente.getText())) {

                cl.setDocumento(Integer.parseInt(jTextFieldDocumentoCliente.getText()));
                cl.setNombre(jTextFieldNombreCliente.getText());
                cl.setApellidos(jTextFieldApellidosCilente.getText());
                cl.setCorreo(jTextFieldCorreoCliente.getText());
                cl.setTelefono(Integer.parseInt(jTextFieldTelefonoCliente.getText()));
                cl.setEmpresa(jTextFieldEmpresaCliente.getText());
                cl.setId(Integer.parseInt(IdCliente.getText()));

                client.ModificarCliente(cl);
                LimpiarTable();
                ListarCliente();

            } else {

                JOptionPane.showMessageDialog(null, "Los campos están vacios");

            }
        }
    }//GEN-LAST:event_jButtonActualizarClienteActionPerformed

    private void jButtonCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearClienteActionPerformed

        if (!"".equals(jTextFieldDocumentoCliente.getText()) && !"".equals(jTextFieldNombreCliente.getText()) && !"".equals(jTextFieldApellidosCilente.getText()) && !"".equals(jTextFieldCorreoCliente.getText()) && !"".equals(jTextFieldTelefonoCliente.getText()) && !"".equals(jTextFieldEmpresaCliente.getText())) {

            cl.setDocumento(Integer.parseInt(jTextFieldDocumentoCliente.getText()));
            cl.setNombre(jTextFieldNombreCliente.getText());
            cl.setApellidos(jTextFieldApellidosCilente.getText());
            cl.setCorreo(jTextFieldCorreoCliente.getText());
            cl.setTelefono(Integer.parseInt(jTextFieldTelefonoCliente.getText()));
            cl.setEmpresa(jTextFieldEmpresaCliente.getText());
            client.RegistarCliente(cl);
            LimpiarTable();
            ListarCliente();
            JOptionPane.showMessageDialog(null, "Cliente REGISTRADO");

        } else {

            JOptionPane.showMessageDialog(null, "Los campos están vacios");

        }
    }//GEN-LAST:event_jButtonCrearClienteActionPerformed

    private void jTableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClienteMouseClicked
        // TODO add your handling code here:

        int fila = jTableCliente.rowAtPoint(evt.getPoint());
        IdCliente.setText(jTableCliente.getValueAt(fila, 0).toString());
        jTextFieldDocumentoCliente.setText(jTableCliente.getValueAt(fila, 1).toString());
        jTextFieldNombreCliente.setText(jTableCliente.getValueAt(fila, 2).toString());
        jTextFieldApellidosCilente.setText(jTableCliente.getValueAt(fila, 3).toString());
        jTextFieldCorreoCliente.setText(jTableCliente.getValueAt(fila, 4).toString());
        jTextFieldTelefonoCliente.setText(jTableCliente.getValueAt(fila, 5).toString());
        jTextFieldEmpresaCliente.setText(jTableCliente.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_jTableClienteMouseClicked

    private void jTextFieldEmpresaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmpresaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmpresaClienteActionPerformed

    private void jTextFieldTelefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoClienteActionPerformed

    private void jTextFieldCorreoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCorreoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCorreoClienteActionPerformed

    private void jButtonEliminarManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarManActionPerformed
        // TODO add your handling code here:
        if (!"".equals(IdMantenimiento.getText())) {

            int pregunta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar?");
            if (pregunta == 0) {

                int id = Integer.parseInt(IdMantenimiento.getText());
                ManDao.EliminarMantenimiento(id);
                LimpiarTable();
                ListarMantenimiento();

            }

        } else {

            JOptionPane.showMessageDialog(null, "Seleccione una fila");

        }
    }//GEN-LAST:event_jButtonEliminarManActionPerformed

    private void jButtonActualizarManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarManActionPerformed
        // TODO add your handling code here:
        if ("".equals(IdMantenimiento.getText())) {

            JOptionPane.showMessageDialog(null, "Seleccione una fila");

        } else {

            if (!"".equals(jTextFieldNinventarioMan.getText()) && !"".equals(jTextFieldIdclienteMan.getText()) && !"".equals(jTextFieldMantenimientoMan.getText()) && !"".equals(jTextFieldDescripcionMan.getText()) && !"".equals(jTextFieldMarcaMan.getText()) && !"".equals(jTextFieldModeloMan.getText()) && !"".equals(jTextFieldSerialMan.getText()) && !"".equals(jTextFieldFeMan.getText())) {

                man.setNinventario(Integer.parseInt(jTextFieldNinventarioMan.getText()));
                man.setIdcliente(Integer.parseInt(jTextFieldIdclienteMan.getText()));
                man.setMantenimiento(jTextFieldMantenimientoMan.getText());
                man.setDescripcion(jTextFieldDescripcionMan.getText());
                man.setMarca(jTextFieldMarcaMan.getText());
                man.setModelo(jTextFieldModeloMan.getText());
                man.setSerial(jTextFieldSerialMan.getText());
                man.setFechaentrada(jTextFieldFeMan.getText());
                man.setFechasalida(jTextFieldFsMan.getText());
                man.setId(Integer.parseInt(IdMantenimiento.getText()));

                ManDao.ModificarMantenimiento(man);
                LimpiarTable();
                ListarMantenimiento();

            } else {

                JOptionPane.showMessageDialog(null, "Los campos están vacios");

            }
        }
    }//GEN-LAST:event_jButtonActualizarManActionPerformed

    private void jButtonCrearManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearManActionPerformed
        // TODO add your handling code here:
        if (!"".equals(jTextFieldNinventarioMan.getText()) && !"".equals(jTextFieldIdclienteMan.getText()) && !"".equals(jTextFieldMantenimientoMan.getText()) && !"".equals(jTextFieldDescripcionMan.getText()) && !"".equals(jTextFieldMarcaMan.getText()) && !"".equals(jTextFieldModeloMan.getText()) && !"".equals(jTextFieldSerialMan.getText()) && !"".equals(jTextFieldFeMan.getText())) {

            man.setNinventario(Integer.parseInt(jTextFieldNinventarioMan.getText()));
            man.setIdcliente(Integer.parseInt(jTextFieldIdclienteMan.getText()));
            man.setMantenimiento(jTextFieldMantenimientoMan.getText());
            man.setDescripcion(jTextFieldDescripcionMan.getText());
            man.setMarca(jTextFieldMarcaMan.getText());
            man.setModelo(jTextFieldModeloMan.getText());
            man.setSerial(jTextFieldSerialMan.getText());
            man.setFechaentrada(jTextFieldFeMan.getText());
            man.setFechasalida(jTextFieldFsMan.getText());

            ManDao.RegistrarMantenimiento(man);
            LimpiarTable();
            ListarMantenimiento();
            JOptionPane.showMessageDialog(null, "Cliente REGISTRADO");

        } else {

            JOptionPane.showMessageDialog(null, "Los campos están vacios");

        }
    }//GEN-LAST:event_jButtonCrearManActionPerformed

    private void jTextFieldB_clienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldB_clienteKeyReleased
        // TODO add your handling code here:
        BuscarCliente(jTextFieldB_cliente.getText());
    }//GEN-LAST:event_jTextFieldB_clienteKeyReleased

    private void jTextFieldB_EmpleadosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldB_EmpleadosKeyReleased
        // TODO add your handling code here:
        BuscarEmpleados(jTextFieldB_Empleados.getText());
    }//GEN-LAST:event_jTextFieldB_EmpleadosKeyReleased

    private void jTextFieldB_MantenimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldB_MantenimientoKeyReleased
        // TODO add your handling code here:
        BuscarMantenimiento(jTextFieldB_Mantenimiento.getText());
    }//GEN-LAST:event_jTextFieldB_MantenimientoKeyReleased

    private void jButtonSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSALIRActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSALIRActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login LG = new Login();
        LG.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaMEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaMEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaMEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaMEC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaMEC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdCliente;
    private javax.swing.JTextField IdEmpleados;
    private javax.swing.JTextField IdMantenimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonActualizarCliente;
    private javax.swing.JButton jButtonActualizarEmpleados;
    private javax.swing.JButton jButtonActualizarMan;
    private javax.swing.JButton jButtonCrearCliente;
    private javax.swing.JButton jButtonCrearEmpleados;
    private javax.swing.JButton jButtonCrearMan;
    private javax.swing.JButton jButtonEliminarCliente;
    private javax.swing.JButton jButtonEliminarEmpleados;
    private javax.swing.JButton jButtonEliminarMan;
    private javax.swing.JButton jButtonSALIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBANNERSIS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTable jTableEmpleados2;
    private javax.swing.JTable jTableMantenimiento;
    private javax.swing.JTextField jTextFieldApellidosCilente;
    private javax.swing.JTextField jTextFieldApellidosEmpleados;
    private javax.swing.JTextField jTextFieldB_Empleados;
    private javax.swing.JTextField jTextFieldB_Mantenimiento;
    private javax.swing.JTextField jTextFieldB_cliente;
    private javax.swing.JTextField jTextFieldCargoEmpleados;
    private javax.swing.JTextField jTextFieldCorreoCliente;
    private javax.swing.JTextField jTextFieldCorreoEmpleados;
    private javax.swing.JTextField jTextFieldDescripcionMan;
    private javax.swing.JTextField jTextFieldDocumentoCliente;
    private javax.swing.JTextField jTextFieldDocumentoEmpleados;
    private javax.swing.JTextField jTextFieldEmpresaCliente;
    private javax.swing.JTextField jTextFieldFeMan;
    private javax.swing.JTextField jTextFieldFsMan;
    private javax.swing.JTextField jTextFieldIdclienteMan;
    private javax.swing.JTextField jTextFieldMantenimientoMan;
    private javax.swing.JTextField jTextFieldMarcaMan;
    private javax.swing.JTextField jTextFieldModeloMan;
    private javax.swing.JTextField jTextFieldNinventarioMan;
    private javax.swing.JTextField jTextFieldNombreCliente;
    private javax.swing.JTextField jTextFieldNombreEmpleados;
    private javax.swing.JTextField jTextFieldSerialMan;
    private javax.swing.JTextField jTextFieldTelefonoCliente;
    private javax.swing.JTextField jTextFieldTelefonoEmpleados;
    // End of variables declaration//GEN-END:variables

    private void LimpiarCliente() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
